### ISSUE TITLE
Attempt to read pk of parent of root instance causes error

### ISSUE THREAD

**Issue by iansprice** [mbraak/django-mptt-admin#111]
With a model such as: 
```
class Product_Line(MPTTModel):
    product_line = models.CharField(max_length=40, null=False, help_text='Product code')
    # ...
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    class Meta:
        ordering = ['product_line', 'short_description']
        verbose_name_plural = u"Product lines"
        verbose_name = u'Product line'
    class MPTTMeta:
        order_insertion_by = ['short_description']
```

django-mptt-admin fails when fetching data for an admin changelist. This only happens once instances are created beyond the root level. 

Full traceback:
`Internal Server Error: /admin/part_numbers/product_line/tree_json/
Traceback (most recent call last):
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django_mptt_admin/admin.py", line 73, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django_mptt_admin/admin.py", line 193, in tree_json_view
    tree_data = self.get_tree_data(qs, max_level)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django_mptt_admin/admin.py", line 173, in get_tree_data
    return util.get_tree_from_queryset(qs, handle_create_node, max_level)
  File "/home/ian/.virtualenvs/THERMALINE/local/lib/python2.7/site-packages/django_mptt_admin/util.py", line 57, in get_tree_from_queryset
    parent_id = getattr(instance.parent, pk_attname)
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by iansprice** [comment]
If anyone runs into this in the future, rebuild your tree. :+1: Thanks for the great library!
